import Prod.Extract
import Prod.Lower
import Prod.Roots
import Prod.Coverage

/-!
# Reusable module export API

The `prod-export` executable is the worked-example frontend.  This module
contains the example-independent part so another Lean package can import
`Prod`, select its own module tree, and produce the same IR, roots, and
coverage artifacts without copying the extractor.
-/

open Lean

namespace Prod

/-- The three artifacts produced for one imported Lean module tree. -/
structure ModuleExport where
  ir : String
  roots : String
  coverage : String

/-- Render `(type ...)` declarations for every user inductive reachable from
    the extracted definitions, deduplicated in a deterministic order. -/
def collectTypeDecls (ctx : LowerCtx) (extracted : Array ExtractedDef)
    : CoreM (Array String) := do
  let env ← getEnv
  let mut wanted : Array Name := #[]
  for ed in extracted do
    if let some decl := ed.decl? then
      for n in declTypeNames env decl do
        if n != ``Nat && n != ``Bool && n != ``Int && n != ``Prod
            && n != ``List && n != ``Option && !wanted.contains n then
          if (env.find? n).isSome then
            wanted := wanted.push n
  let sorted := wanted.qsort fun a b => Name.quickCmp a b == .lt
  let mut out : Array String := #[]
  for n in sorted do
    let (rendered, _) ← (((lowerTypeDecl n).run ctx).run {})
    if let some sexp := rendered then out := out.push sexp
  return out

/-- Assemble one complete IR module and its per-definition coverage reports. -/
def emitKernelIr (ctx : LowerCtx) (irModule : String) (extracted : Array ExtractedDef)
    : CoreM (String × Array DefReport) := do
  let mut ir := s!";; Generated by prod-export: LCNF → sexp IR.\n(module {irModule}\n"
  let typeDecls ← collectTypeDecls ctx extracted
  for decl in typeDecls do
    ir := ir ++ "\n" ++ indent 2 decl ++ "\n"
  let mut reports : Array DefReport := #[]
  for ed in extracted do
    match ed.decl? with
    | some decl =>
      let (sexp, st) ← lowerDecl ctx decl
      let arityNote := if st.dropped == 0 then "" else s!"\n  ;; arity: {st.dropped} erased/type args dropped"
      ir := ir ++ s!"\n  ;; full: {ed.name}{arityNote}\n" ++ indent 2 sexp ++ "\n"
      reports := reports.push
        { name := ed.name, lowered := true, opaques := st.opaques, externs := st.externs }
    | none =>
      reports := reports.push { name := ed.name, lowered := false, skipReason := ed.skipReason }
  return (ir ++ ")\n", reports)

/-- Export all `@[prod]` declarations owned by `moduleRoot` from an already
    imported environment.  External packages normally call this after
    `Lean.importModules`, as demonstrated by the pinned UOR fixture. -/
def exportModule (moduleRoot : Name) (irModule : String) : CoreM ModuleExport := do
  let env ← getEnv
  let ctx : LowerCtx := { tagged := (taggedNames env moduleRoot).toArray }
  let extracted ← extractTagged moduleRoot
  let (ir, reports) ← emitKernelIr ctx irModule extracted
  let own := ownConstants env moduleRoot
  return {
    ir
    roots := rootsJson (← computeRoots own)
    coverage := ← buildCoverage moduleRoot own reports
  }

end Prod
