//! Import-free Hologram Core-Wasm v1 adapter package generation.

use alloc::format;
use alloc::string::{String, ToString};
use sha2::{Digest, Sha256};

use prod_ir::{Module, Type};

use crate::{generate_module, Error, GeneratedPackage, PackageFile};

/// Closed generic ABI parameters. Application behavior remains in `entry`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CoreWasmSpec {
    pub crate_name: String,
    pub entry: String,
    pub export_name: String,
    pub input_allocation_cap: u32,
    pub output_allocation_cap: u32,
    pub maximum_pages: u32,
    pub input_ir_sha256: String,
}

fn file(path: &str, text: String) -> PackageFile {
    PackageFile {
        path: path.to_string(),
        bytes: text.into_bytes(),
    }
}

fn sha256(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn valid_ident(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value.bytes().enumerate().all(|(index, byte)| {
            byte.is_ascii_alphabetic() || byte == b'_' || (index > 0 && byte.is_ascii_digit())
        })
}

fn valid_crate(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 64
        && value.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-' || byte == b'_'
        })
        && value.as_bytes()[0].is_ascii_lowercase()
}

/// Generate the source package for an import-free Core-Wasm v1 guest. The
/// selected function must have either the allocation-free byte-list signature
/// that prod-codegen renders as `(&[u8], &mut [u8]) -> Result<usize, _>`, or
/// the owned `Bytes -> Bytes` signature used by typed UTF-8 codecs.
pub fn generate_core_wasm_package(
    module: &Module,
    spec: &CoreWasmSpec,
) -> Result<GeneratedPackage, Error> {
    if !valid_crate(&spec.crate_name)
        || !valid_ident(&spec.entry)
        || !valid_ident(&spec.export_name)
        || spec.input_ir_sha256.len() != 64
        || !spec
            .input_ir_sha256
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    {
        return Err(Error::OpaqueType(
            "invalid Core-Wasm target name".to_string(),
        ));
    }
    if spec.input_allocation_cap == 0
        || spec.output_allocation_cap == 0
        || spec.maximum_pages == 0
        || spec.maximum_pages > 32_767
    {
        return Err(Error::OpaqueType(
            "invalid Core-Wasm resource bound".to_string(),
        ));
    }
    let definition = module
        .definitions
        .iter()
        .find(|definition| definition.name == spec.entry)
        .ok_or_else(|| Error::UnresolvedCall(spec.entry.clone()))?;
    let byte_list = Type::List(alloc::boxed::Box::new(Type::UInt8));
    let list_entry = definition.params.len() == 1
        && definition.params[0].1 == byte_list
        && definition.ret == byte_list;
    let bytes_entry = definition.params.len() == 1
        && definition.params[0].1 == Type::Bytes
        && definition.ret == Type::Bytes;
    if !list_entry && !bytes_entry {
        return Err(Error::UnsupportedList(
            "Core-Wasm entry must be (List UInt8) -> List UInt8 or Bytes -> Bytes".to_string(),
        ));
    }
    let generated = generate_module(module)?;
    let maximum_memory = u64::from(spec.maximum_pages) * 65_536;
    let cargo = format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\ncrate-type = [\"cdylib\"]\npath = \"src/lib.rs\"\n\n[profile.release]\npanic = \"abort\"\nopt-level = \"s\"\nlto = true\ncodegen-units = 1\nstrip = \"symbols\"\n",
        spec.crate_name
    );
    let lock = format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"{}\"\nversion = \"0.1.0\"\n",
        spec.crate_name
    );
    let config = format!(
        "[build]\ntarget = \"wasm32-unknown-unknown\"\n\n[target.wasm32-unknown-unknown]\nrustflags = [\"-C\", \"link-arg=--export-memory\", \"-C\", \"link-arg=--max-memory={maximum_memory}\", \"-C\", \"link-arg=-zstack-size=65536\"]\n"
    );
    let invoke_entry = if list_entry {
        format!(
            "let output_ptr = allocate(OUTPUT_CAP, 8);\n    let output_end = output_ptr.checked_add(OUTPUT_CAP).unwrap_or_else(|| trap());\n    if input_ptr < output_end && output_ptr < input_end {{ trap(); }}\n    let output = unsafe {{ core::slice::from_raw_parts_mut(output_ptr as *mut u8, OUTPUT_CAP as usize) }};\n    let output_len = {entry}(input, output).unwrap_or_else(|_| trap());\n    if output_len > OUTPUT_CAP as usize {{ trap(); }}",
            entry = spec.entry,
        )
    } else {
        format!(
            "let generated_output = {entry}(input.to_vec());\n    if generated_output.len() > OUTPUT_CAP as usize {{ trap(); }}\n    let output_len = generated_output.len();\n    let output_ptr = allocate(u32::try_from(output_len).unwrap_or_else(|_| trap()), 8);\n    let output_end = output_ptr.checked_add(u32::try_from(output_len).unwrap_or_else(|_| trap())).unwrap_or_else(|| trap());\n    if input_ptr < output_end && output_ptr < input_end {{ trap(); }}\n    unsafe {{ core::ptr::copy_nonoverlapping(generated_output.as_ptr(), output_ptr as *mut u8, output_len); }}",
            entry = spec.entry,
        )
    };
    let source = format!(
        r#"#![no_std]
#![allow(dead_code, non_snake_case, unused_parens, unused_variables)]
extern crate alloc;

use core::alloc::{{GlobalAlloc, Layout}};
use core::sync::atomic::{{AtomicU32, Ordering}};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ComputeError {{
    AddOverflow,
    MulOverflow,
    ShiftExponentTooLarge,
    ShiftOverflow,
    PowExponentTooLarge,
    PowOverflow,
    OutputTooSmall,
}}

{generated}

const INPUT_CAP: u32 = {input_cap};
const OUTPUT_CAP: u32 = {output_cap};
const MAXIMUM_PAGES: u32 = {maximum_pages};
static NEXT: AtomicU32 = AtomicU32::new(0);

struct BumpAllocator;

#[global_allocator]
static GLOBAL_ALLOCATOR: BumpAllocator = BumpAllocator;

extern "C" {{ static __heap_base: u8; }}

#[inline(always)]
fn trap() -> ! {{ core::arch::wasm32::unreachable() }}

#[inline(always)]
fn align_to(value: u32, alignment: u32) -> u32 {{
    if alignment < 8 || !alignment.is_power_of_two() {{ trap(); }}
    value.checked_add(alignment - 1)
        .map(|aligned| aligned & !(alignment - 1))
        .unwrap_or_else(|| trap())
}}

#[inline(always)]
fn heap_base() -> u32 {{
    align_to(core::ptr::addr_of!(__heap_base) as u32, 8)
}}

#[inline(always)]
fn ensure_memory(required: u32) {{
    let pages = core::arch::wasm32::memory_size::<0>() as u32;
    if pages > MAXIMUM_PAGES {{ trap(); }}
    let current = pages.checked_mul(65_536).unwrap_or_else(|| trap());
    if required <= current {{ return; }}
    let missing = required.checked_sub(current).unwrap_or_else(|| trap());
    let grow = missing.checked_add(65_535).map(|value| value / 65_536).unwrap_or_else(|| trap());
    let target = pages.checked_add(grow).unwrap_or_else(|| trap());
    if target > MAXIMUM_PAGES {{ trap(); }}
    if core::arch::wasm32::memory_grow::<0>(grow as usize) == usize::MAX {{ trap(); }}
}}

fn allocate(size: u32, alignment: u32) -> u32 {{
    loop {{
        let prior = NEXT.load(Ordering::Relaxed);
        let start = align_to(prior.max(heap_base()), alignment.max(8));
        let end = start.checked_add(size).unwrap_or_else(|| trap());
        let required = if size == 0 {{ start.checked_add(1).unwrap_or_else(|| trap()) }} else {{ end }};
        ensure_memory(required);
        if NEXT.compare_exchange_weak(prior, end, Ordering::Relaxed, Ordering::Relaxed).is_ok() {{
            return start;
        }}
    }}
}}

unsafe impl GlobalAlloc for BumpAllocator {{
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {{
        let size = u32::try_from(layout.size()).unwrap_or_else(|_| trap());
        let alignment = u32::try_from(layout.align()).unwrap_or_else(|_| trap());
        allocate(size, alignment) as *mut u8
    }}

    unsafe fn dealloc(&self, _pointer: *mut u8, _layout: Layout) {{}}
}}

#[no_mangle]
pub extern "C" fn holo_alloc(size: i32) -> i32 {{
    if size < 0 {{ trap(); }}
    let size = size as u32;
    if size > INPUT_CAP {{ trap(); }}
    let start = allocate(size, 8);
    i32::try_from(start).unwrap_or_else(|_| trap())
}}

#[no_mangle]
pub extern "C" fn {export_name}(input_ptr: i32, input_len: i32) -> i64 {{
    if input_ptr < 0 || input_len < 0 {{ trap(); }}
    let input_ptr = input_ptr as u32;
    let input_len = input_len as u32;
    if input_len > INPUT_CAP {{ trap(); }}
    let input_end = input_ptr.checked_add(input_len).unwrap_or_else(|| trap());
    let memory_bytes = (core::arch::wasm32::memory_size::<0>() as u32)
        .checked_mul(65_536).unwrap_or_else(|| trap());
    if input_end > memory_bytes {{ trap(); }}

    let input = unsafe {{ core::slice::from_raw_parts(input_ptr as *const u8, input_len as usize) }};
    {invoke_entry}
    let packed = (u64::from(output_ptr) << 32) | u64::try_from(output_len).unwrap_or_else(|_| trap());
    packed as i64
}}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo<'_>) -> ! {{ trap() }}
"#,
        generated = generated,
        input_cap = spec.input_allocation_cap,
        output_cap = spec.output_allocation_cap,
        maximum_pages = spec.maximum_pages,
        export_name = spec.export_name,
        invoke_entry = invoke_entry,
    );
    let mut files = alloc::vec![
        file(".cargo/config.toml", config),
        file("Cargo.lock", lock),
        file("Cargo.toml", cargo),
        file("src/lib.rs", source),
    ];
    let records = files
        .iter()
        .map(|item| {
            format!(
                "{{\"path\":\"{}\",\"sha256\":\"{}\"}}",
                item.path,
                sha256(&item.bytes)
            )
        })
        .collect::<alloc::vec::Vec<_>>()
        .join(",");
    let manifest = format!(
        "{{\"entry\":\"{}\",\"export\":\"{}\",\"files\":[{}],\"input_allocation_cap\":{},\"input_ir_sha256\":\"{}\",\"maximum_pages\":{},\"output_allocation_cap\":{},\"schema\":\"lean4-prod/core-wasm-target/1\"}}\n",
        spec.entry,
        spec.export_name,
        records,
        spec.input_allocation_cap,
        spec.input_ir_sha256,
        spec.maximum_pages,
        spec.output_allocation_cap,
    );
    files.push(file("generation-manifest.json", manifest));
    files.sort_by(|left, right| left.path.as_bytes().cmp(right.path.as_bytes()));
    Ok(GeneratedPackage { files })
}
