//! prod-cli: Command-line tool for parsing Lean 4 IR and generating Rust
//!
//! Usage:
//!   prod parse module.ir
//!   prod gen module.ir [--output generated.rs]
//!   prod validate module.ir

mod roots;

use clap::{Parser, Subcommand, ValueEnum};
use std::fs;
use std::path::Path;

#[derive(Parser)]
#[command(name = "prod")]
#[command(about = "Lean 4 → prod IR parser and Rust code generator")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Parse an IR file and print its AST
    Parse {
        /// Path to the IR file
        path: String,
    },
    /// Generate Rust code from an IR file (prints to stdout unless --output is given)
    Gen {
        /// Path to the IR file
        path: String,
        /// Output path for generated Rust code
        #[arg(short, long)]
        output: Option<String>,
    },
    /// Generate a C header and matching Rust `extern "C"` wrappers.
    Header {
        /// Path to the IR file
        path: String,
        /// Output path for the generated C header
        #[arg(short, long)]
        output: String,
        /// Output path for the matching Rust wrapper source
        #[arg(long)]
        rust_output: String,
    },
    /// Generate C, Rust, Python, TypeScript, Kotlin, and WebAssembly SDK artifacts.
    Sdks {
        /// Path to the exported IR file
        path: String,
        /// Root directory for generated SDK bundles
        #[arg(short, long, default_value = "output")]
        output: String,
        /// Bundle name and generated artifact stem
        #[arg(long, default_value = "lean4-prod")]
        stem: String,
        /// Native library name used by the Rust/Kotlin SDKs
        #[arg(long, default_value = "lean4_prod")]
        library_name: String,
    },
    /// Generate SDK artifacts for one language only.
    Sdk {
        /// Path to the exported IR file
        path: String,
        /// Language artifact to generate
        #[arg(value_enum, short, long)]
        language: SdkLanguage,
        /// Root directory for generated SDK artifacts
        #[arg(short, long, default_value = "output")]
        output: String,
        /// Bundle name and generated artifact stem
        #[arg(long, default_value = "lean4-prod")]
        stem: String,
        /// Native library name used by the Rust/Kotlin SDKs
        #[arg(long, default_value = "lean4_prod")]
        library_name: String,
    },
    /// Validate an IR file (check for unsupported constructs)
    Validate {
        /// Path to the IR file
        path: String,
    },
    /// Analyze proof roots exported by Lean.
    Roots {
        #[command(subcommand)]
        command: RootCommands,
    },
    /// Render the published Lean-for-production subset contract.
    Subset {
        /// Path to subset.json, written by prod-export
        path: String,
        /// Output path for the rendered markdown
        #[arg(short, long)]
        output: Option<String>,
    },
}

#[derive(Clone, ValueEnum)]
enum SdkLanguage {
    C,
    Rust,
    Python,
    Typescript,
    Kotlin,
    Wasm,
}

/// The Lean half of the subset contract, written by `prod-export`
/// (`Prod.subsetJson`, `lean/Prod/Emit.lean`).
#[derive(Debug, serde::Deserialize)]
struct SubsetFile {
    operators: Vec<String>,
    deciders: Vec<String>,
    types: Vec<String>,
}

/// Render the published subset contract: the Lean half (`subset.json`,
/// what `Lower.lean` accepts) merged with the Rust half (`prod_codegen::
/// REJECTIONS`, what `Error` reports). Generated, never hand-written: a
/// hand-maintained contract drifts from the implementation, and a drifted
/// contract is worse than none.
fn render_subset(subset: &SubsetFile) -> String {
    let mut out = String::from(
        "# Lean-for-production: the supported subset\n\n\
         <!-- GENERATED by `just subset`. Do not edit by hand. -->\n\n\
         This is the fragment of Lean 4 that `prod-export` lowers and\n\
         `prod-codegen` renders. Anything outside it is rejected with the\n\
         named error rather than silently mis-compiled.\n\n\
         ## Types\n\n",
    );
    for t in &subset.types {
        out.push_str(&format!("- `{}`\n", t));
    }
    out.push_str(
        "\n**Erased invariants.** A Lean structure may carry `Prop` fields\n\
         expressing invariants over the computational fields — for example\n\
         `UorAtlas.Instance.valid : q ≥ 1 ∧ T ≥ 1 ∧ O ≥ 1`. `Prop` fields are\n\
         erased on export, correctly: they are proofs, not data, and carry no\n\
         runtime representation. The consequence is that the generated Rust\n\
         struct does **not** enforce the invariant — `Instance { q: 0, T: 0,\n\
         O: 0 }` is constructible in Rust where the Lean type forbids it.\n\
         Callers that need the invariant must re-check it in Rust; the\n\
         generated struct is a plain data carrier, not a refinement type.\n",
    );
    out.push_str("\n## Operators\n\n");
    for op in &subset.operators {
        out.push_str(&format!("- `{}`\n", op));
    }
    out.push_str("\n## Decidable guards\n\n");
    for d in &subset.deciders {
        out.push_str(&format!("- `{}`\n", d));
    }
    out.push_str(
        "\n## Rejections\n\nEverything else fails, precisely:\n\n| Error | Cause |\n|---|---|\n",
    );
    for (variant, cause) in prod_codegen::REJECTIONS {
        out.push_str(&format!("| `{}` | {} |\n", variant, cause));
    }
    out
}

#[derive(Subcommand)]
enum RootCommands {
    /// Check dependency acyclicity and root dependency coverage.
    Check {
        path: String,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
    /// Print roots on the Pareto front of proof size, kernel depth, and check time.
    Pareto {
        path: String,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
    /// Generate bridges between roots sharing kernel dependencies.
    Connect {
        path: String,
        root1: Option<String>,
        root2: Option<String>,
        /// Include auto-generated roots (default: hand-written roots only)
        #[arg(long)]
        all: bool,
    },
}

/// Collect every unresolved callee name reachable from an expression.
///
/// The traversal is `prod_ir::Expr::children()`, not a copy of it: this used
/// to hand-match every recursive shape and had already drifted (it never
/// looked inside `Expr::Shr`, added later), so `prod validate` could report a
/// clean bill of health for IR containing an extern call.
fn collect_externs(expr: &prod_ir::Expr, out: &mut Vec<String>) {
    if let prod_ir::Expr::Extern(name, _) = expr {
        out.push(name.clone());
    }
    for child in expr.children() {
        collect_externs(child, out);
    }
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Parse { path } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));
            println!("Module: {}", module.name);
            for def in &module.definitions {
                println!("  Def: {} -> {:?}", def.name, def.ret);
                println!("    Params: {:?}", def.params);
                println!("    Body: {:?}", def.body);
            }
        }
        Commands::Gen { path, output } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));

            let body = prod_codegen::generate_module(&module)
                .unwrap_or_else(|e| panic!("Codegen error: {}", e));

            let mut out = String::from("#![allow(dead_code)]\n\n");
            out.push_str(&format!(
                "// Generated from Lean 4 module: {}\n\n",
                module.name
            ));
            out.push_str(&body);

            match output {
                Some(output) => {
                    fs::write(&output, out)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", output, e));
                    println!("Generated: {}", output);
                }
                None => print!("{}", out),
            }
        }
        Commands::Header {
            path,
            output,
            rust_output,
        } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));
            let bindings = prod_codegen::generate_c_bindings(&module)
                .unwrap_or_else(|e| panic!("C ABI generation error: {}", e));
            fs::write(&output, bindings.header)
                .unwrap_or_else(|e| panic!("Failed to write {}: {}", output, e));
            fs::write(&rust_output, bindings.rust)
                .unwrap_or_else(|e| panic!("Failed to write {}: {}", rust_output, e));
            println!("Generated: {}", output);
            println!("Generated: {}", rust_output);
        }
        Commands::Sdks {
            path,
            output,
            stem,
            library_name,
        } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));
            let bindings = prod_codegen::generate_sdks(&module, &library_name)
                .unwrap_or_else(|e| panic!("SDK generation error: {}", e));
            let root = Path::new(&output).join(&stem);
            let c_dir = root.join("c");
            let rust_dir = root.join("rust");
            let python_dir = root.join("python");
            let typescript_dir = root.join("typescript");
            let kotlin_dir = root.join("kotlin");
            let wasm_dir = root.join("wasm");
            for directory in [
                &c_dir,
                &rust_dir,
                &python_dir,
                &typescript_dir,
                &kotlin_dir,
                &wasm_dir,
            ] {
                fs::create_dir_all(directory)
                    .unwrap_or_else(|e| panic!("Failed to create {}: {}", directory.display(), e));
            }
            fs::write(c_dir.join(format!("{}.h", stem)), bindings.c_header)
                .unwrap_or_else(|e| panic!("Failed to write C header: {}", e));
            fs::write(c_dir.join(format!("{}_ffi.rs", stem)), bindings.c_wrapper)
                .unwrap_or_else(|e| panic!("Failed to write C Rust wrapper: {}", e));
            fs::write(rust_dir.join("lib.rs"), bindings.rust)
                .unwrap_or_else(|e| panic!("Failed to write Rust SDK: {}", e));
            fs::write(
                python_dir.join(format!("{}.py", stem.replace('-', "_"))),
                bindings.python,
            )
            .unwrap_or_else(|e| panic!("Failed to write Python SDK: {}", e));
            fs::write(typescript_dir.join("index.ts"), bindings.typescript)
                .unwrap_or_else(|e| panic!("Failed to write TypeScript SDK: {}", e));
            fs::write(kotlin_dir.join("Lean4Prod.kt"), bindings.kotlin)
                .unwrap_or_else(|e| panic!("Failed to write Kotlin SDK: {}", e));
            fs::write(wasm_dir.join("lib.rs"), bindings.wasm)
                .unwrap_or_else(|e| panic!("Failed to write WebAssembly SDK: {}", e));
            println!("Generated SDK bundle: {}", root.display());
        }
        Commands::Sdk {
            path,
            language,
            output,
            stem,
            library_name,
        } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let (_, module) = prod_ir::parser::parse_module(&content)
                .unwrap_or_else(|e| panic!("Parse error: {:?}", e));
            let bindings = prod_codegen::generate_sdks(&module, &library_name)
                .unwrap_or_else(|e| panic!("SDK generation error: {}", e));
            let root = Path::new(&output).join(&stem);

            match language {
                SdkLanguage::C => {
                    let directory = root.join("c");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let header = directory.join(format!("{}.h", stem));
                    let wrapper = directory.join(format!("{}_ffi.rs", stem));
                    fs::write(&header, bindings.c_header)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", header.display(), e));
                    fs::write(&wrapper, bindings.c_wrapper)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", wrapper.display(), e));
                    println!(
                        "Generated C SDK: {} and {}",
                        header.display(),
                        wrapper.display()
                    );
                }
                SdkLanguage::Rust => {
                    let directory = root.join("rust");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let path = directory.join("lib.rs");
                    fs::write(&path, bindings.rust)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", path.display(), e));
                    println!("Generated Rust SDK: {}", path.display());
                }
                SdkLanguage::Python => {
                    let directory = root.join("python");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let path = directory.join(format!("{}.py", stem.replace('-', "_")));
                    fs::write(&path, bindings.python)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", path.display(), e));
                    println!("Generated Python SDK: {}", path.display());
                }
                SdkLanguage::Typescript => {
                    let directory = root.join("typescript");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let path = directory.join("index.ts");
                    fs::write(&path, bindings.typescript)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", path.display(), e));
                    println!("Generated TypeScript SDK: {}", path.display());
                }
                SdkLanguage::Kotlin => {
                    let directory = root.join("kotlin");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let path = directory.join("Lean4Prod.kt");
                    fs::write(&path, bindings.kotlin)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", path.display(), e));
                    println!("Generated Kotlin SDK: {}", path.display());
                }
                SdkLanguage::Wasm => {
                    let directory = root.join("wasm");
                    fs::create_dir_all(&directory).unwrap_or_else(|e| {
                        panic!("Failed to create {}: {}", directory.display(), e)
                    });
                    let path = directory.join("lib.rs");
                    fs::write(&path, bindings.wasm)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", path.display(), e));
                    println!("Generated WebAssembly SDK: {}", path.display());
                }
            }
        }
        Commands::Validate { path } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            match prod_ir::parser::parse_module(&content) {
                Ok((_, module)) => {
                    println!(
                        "✓ Valid IR: {} definitions in module '{}'",
                        module.definitions.len(),
                        module.name
                    );
                    let opaque: Vec<_> = module
                        .definitions
                        .iter()
                        .filter(|d| matches!(d.body, prod_ir::Expr::Opaque(_)))
                        .collect();
                    if !opaque.is_empty() {
                        println!("⚠ {} definitions contain opaque expressions", opaque.len());
                    }
                    let mut unresolved: Vec<String> = Vec::new();
                    for def in &module.definitions {
                        collect_externs(&def.body, &mut unresolved);
                    }
                    unresolved.sort();
                    unresolved.dedup();
                    if !unresolved.is_empty() {
                        println!("✗ {} unresolved call(s):", unresolved.len());
                        for name in &unresolved {
                            println!("    {}", name);
                        }
                        std::process::exit(1);
                    }
                }
                Err(e) => {
                    eprintln!("✗ Invalid IR: {:?}", e);
                    std::process::exit(1);
                }
            }
        }
        Commands::Roots { command } => match command {
            RootCommands::Check { path, all } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let report = roots::check(&roots);
                println!(
                    "Loaded {} roots{}.",
                    roots.len(),
                    if all {
                        " (including auto-generated)"
                    } else {
                        ""
                    }
                );
                println!(
                    "Checking dependency acyclicity... {}",
                    if report.acyclic { "OK" } else { "FAILED" }
                );
                println!(
                    "Roots with empty dependencies: {}",
                    report.empty_dependencies.len()
                );
                if !report.duplicate_ids.is_empty() {
                    println!(
                        "Warning: duplicate root ids: {}",
                        report.duplicate_ids.join(", ")
                    );
                }
                if report.acyclic && report.empty_dependencies.is_empty() {
                    println!("All root checks passed.");
                } else {
                    std::process::exit(1);
                }
            }
            RootCommands::Pareto { path, all } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let front = roots::pareto_front(&roots);
                println!("Pareto front: {} roots", front.len());
                for idx in front {
                    let root = &roots[idx];
                    println!(
                        "  {} [{}] (proof_term_size={}, kernel_depth={}, check_time_ns={})",
                        roots::short_name(&root.id),
                        root.id,
                        root.proof_term_size,
                        root.kernel_depth,
                        root.check_time_ns
                    );
                }
            }
            RootCommands::Connect {
                path,
                root1,
                root2,
                all,
            } => {
                let roots = roots::load(&path).unwrap_or_else(|e| panic!("{e}"));
                let roots = roots::filter_roots(roots, all);
                let candidates = roots::bridges(&roots);
                let selected = match (root1, root2) {
                    (Some(a), Some(b)) => candidates
                        .into_iter()
                        .filter(|bridge| {
                            (roots::id_matches(&roots[bridge.left].id, &a)
                                && roots::id_matches(&roots[bridge.right].id, &b))
                                || (roots::id_matches(&roots[bridge.left].id, &b)
                                    && roots::id_matches(&roots[bridge.right].id, &a))
                        })
                        .collect(),
                    (None, None) => candidates,
                    _ => {
                        eprintln!("connect expects either zero or two root ids");
                        std::process::exit(2);
                    }
                };
                for bridge in &selected {
                    let left = roots::short_name(&roots[bridge.left].id);
                    let right = roots::short_name(&roots[bridge.right].id);
                    println!("bridge_{left}_{right}: {left} ↔ {right}");
                    println!("  shared kernel dependencies: {}", bridge.shared.join(", "));
                }
                println!("Generated {} bridge hypotheses.", selected.len());
            }
        },
        Commands::Subset { path, output } => {
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path, e));
            let subset: SubsetFile = serde_json::from_str(&content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", path, e));
            let rendered = render_subset(&subset);
            match output {
                Some(output) => {
                    fs::write(&output, &rendered)
                        .unwrap_or_else(|e| panic!("Failed to write {}: {}", output, e));
                    println!("Generated: {}", output);
                }
                None => print!("{}", rendered),
            }
        }
    }
}
